[package]
name = "rust-nested-macro-repetition"
version = "0.1.0"
authors = ["Daniel Chiquito <daniel.chiquito@kitware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
